# Generated by Django 4.0 on 2022-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
